### PR TITLE
Add YouTube link

### PR DESCRIPTION
**Pull request by annajung**
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>

- PR to test https://github.com/SAME-Project/same-project/issues/61#event-6311428443
- Add YouTube link

### CODE REVIEW

**Comment by annajung** [comment]
@lukemarsden Could you add `ok-to-test` label to test if the GitHub actions are working as expected? Looks like https://github.com/SAME-Project/same-project/pull/84 from @Bubblyworld might have fixed it.

**Comment by annajung** [comment]
Looks like it works as expected! Closing out the PR

**Comment by Bubblyworld** [comment]
@annajung one thing I noticed is that the build/test actions are running against the base branch, rather than the pull-request branch, is that the intention?

**Comment by annajung** [comment]
Thanks for pointing this out! That was not the intention and I was testing and debating on if ref should be added to the checkout step and somehow got totally missed it in the PR.

Do you have feedback on adding explicit PR checkout with pull_request_target? Or is there a better way to handle it without explicit target?

**Comment by Bubblyworld** [comment]
An explicit checkout sounds good to me, seems like what everyone does to get around this! Boy, github actions make it kinda hard to work with external PRs 😅

**Comment by Bubblyworld** [comment]
https://github.com/SAME-Project/same-project/pull/91

**Pull request closed without merging**
